# Default values.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
strategy:
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

# imagePullSecrets:
#   - name: regcred
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
  #  kubernetes.io/ingress.class: "nginx"
  #  cert-manager.io/cluster-issuer: "le-prod"
  #  external-dns.alpha.kubernetes.io/hostname: "test-dw.loc.local.domain"
  #  external-dns.alpha.kubernetes.io/target: "dw.loc.local.domain"
  #  external-dns.alpha.kubernetes.io/ttl: "60"
  hosts: []
  #  - host: "dw.loc.local.domain"
  #    paths:
  #      - /
  # tls:
  #   - secretName: "dw-loc-le-prod-tls"
  #     hosts:
  #       - "dw.loc.local.domain"

resources:
  requests:
    memory: "10Mi"
    cpu: "25m"
  limits:
    memory: "20Mi"
    cpu: "50m"

nodeSelector: {}

tolerations: []

affinity: {}
